### ISSUE TITLE
在 头文件中已经定义 TYPE_RISCV_QUARD_STAR_MACHINE 

### ISSUE THREAD

**Issue by later-3** [QQxiaoming/quard_star_tutorial#12]
https://github.com/QQxiaoming/quard_star_tutorial/blob/067fcb55b08273b9957001b6022509d2cfb6f231/qemu-7.0.0/hw/riscv/quard_star.c#L684

**Comment by QQxiaoming** [comment]
我已经将它们修复了。

顺便提一下，如果你有兴趣，在发现这种明显的代码改进点时，可以直接修改它们并向我发送Pull requests吗？

**Comment by later-3** [comment]
> 我已经将它们修复了。
> 
> 顺便提一下，如果你有兴趣，在发现这种明显的代码改进点时，可以直接修改它们并向我发送Pull requests吗？

OK
