### ISSUE TITLE
trusted_domain load error

### ISSUE THREAD

**Issue by zhutang** [QQxiaoming/quard_star_tutorial#20]
hi, when i use ./build.sh trusted_domain, i got this error:

CC lseek.o
CC fstat.o
CC sbrk.o
CC sbi.o
CC it.o
CC main.o
AS startup.o
AS portASM.o
LD trusted_fw.elf
/opt/gcc-riscv64-unknown-elf/bin/../lib/gcc/riscv64-unknown-elf/12.2.0/../../../../riscv64-unknown-elf/bin/ld: warning: build/trusted_fw.elf has a LOAD segment with RWX permissions
/opt/gcc-riscv64-unknown-elf/bin/../lib/gcc/riscv64-unknown-elf/12.2.0/../../../../riscv64-unknown-elf/lib/libc.a(lib_a-svfprintf.o): in function `_svfprintf_r':
vfprintf.c:(.text._svfprintf_r+0x68): relocation truncated to fit: R_RISCV_HI20 against `.L20'
/opt/gcc-riscv64-unknown-elf/bin/../lib/gcc/riscv64-unknown-elf/12.2.0/../../../../riscv64-unknown-elf/lib/libc.a(lib_a-ldtoa.o): in function `.L298':
ldtoa.c:(.text.ediv+0x64): relocation truncated to fit: R_RISCV_HI20 against `ezero'
/opt/gcc-riscv64-unknown-elf/bin/../lib/gcc/riscv64-unknown-elf/12.2.0/../../../../riscv64-unknown-elf/lib/libc.a(lib_a-ldtoa.o): in function `.L415':
ldtoa.c:(.text.emul+0x66): relocation truncated to fit: R_RISCV_HI20 against `ezero'
/opt/gcc-riscv64-unknown-elf/bin/../lib/gcc/riscv64-unknown-elf/12.2.0/../../../../riscv64-unknown-elf/lib/libc.a(lib_a-ldtoa.o): in function `.L534':
ldtoa.c:(.text._ldtoa_r+0xe8): relocation truncated to fit: R_RISCV_HI20 against `eone'
/opt/gcc-riscv64-unknown-elf/bin/../lib/gcc/riscv64-unknown-elf/12.2.0/../../../../riscv64-unknown-elf/lib/libc.a(lib_a-assert.o): in function `__assert_func':
assert.c:(.text.__assert_func+0x1a): relocation truncated to fit: R_RISCV_HI20 against `.LC0'
/opt/gcc-riscv64-unknown-elf/bin/../lib/gcc/riscv64-unknown-elf/12.2.0/../../../../riscv64-unknown-elf/lib/libc.a(lib_a-locale.o): in function `__locale_mb_cur_max':
locale.c:(.text.__locale_mb_cur_max+0x0): relocation truncated to fit: R_RISCV_HI20 against symbol `__global_locale' defined in .data.__global_locale section in /opt/gcc-riscv64-unknown-elf/bin/../lib/gcc/riscv64-unknown-elf/12.2.0/../../../../riscv64-unknown-elf/lib/libc.a(lib_a-locale.o)
/opt/gcc-riscv64-unknown-elf/bin/../lib/gcc/riscv64-unknown-elf/12.2.0/../../../../riscv64-unknown-elf/lib/libc.a(lib_a-vfiprintf.o): in function `.L28':
vfprintf.c:(.text._vfiprintf_r+0x6a): relocation truncated to fit: R_RISCV_HI20 against `.L46'
/opt/gcc-riscv64-unknown-elf/bin/../lib/gcc/riscv64-unknown-elf/12.2.0/../../../../riscv64-unknown-elf/lib/libc.a(lib_a-fini.o): in function `__libc_fini_array':
fini.c:(.text.__libc_fini_array+0x4): relocation truncated to fit: R_RISCV_HI20 against symbol `__fini_array_start' defined in .text section in build/trusted_fw.elf
/opt/gcc-riscv64-unknown-elf/bin/../lib/gcc/riscv64-unknown-elf/12.2.0/../../../../riscv64-unknown-elf/lib/libc.a(lib_a-init.o): in function `__libc_init_array':
init.c:(.text.__libc_init_array+0x4): relocation truncated to fit: R_RISCV_HI20 against symbol `__preinit_array_end' defined in .text section in build/trusted_fw.elf
/opt/gcc-riscv64-unknown-elf/bin/../lib/gcc/riscv64-unknown-elf/12.2.0/../../../../riscv64-unknown-elf/lib/libc.a(lib_a-freer.o): in function `_malloc_trim_r':
mallocr.c:(.text._malloc_trim_r+0x4): relocation truncated to fit: R_RISCV_HI20 against symbol `__malloc_av_' defined in .data.__malloc_av_ section in /opt/gcc-riscv64-unknown-elf/bin/../lib/gcc/riscv64-unknown-elf/12.2.0/../../../../riscv64-unknown-elf/lib/libc.a(lib_a-mallocr.o)
/opt/gcc-riscv64-unknown-elf/bin/../lib/gcc/riscv64-unknown-elf/12.2.0/../../../../riscv64-unknown-elf/lib/libc.a(lib_a-freer.o): in function `_free_r':
mallocr.c:(.text._free_r+0x1c): 从输出所省略的额外重寻址溢出
collect2: error: ld returned 1 exit status
make: *** [Makefile:151：build/trusted_fw.elf] 错误 1

The other ./build cmds work fine.
my OS is ubuntun 20.04
riscv compiler is:
- [riscv64-elf-ubuntu-20.04-nightly-2023.02.25-nightly.tar.gz](https://github.com/riscv-collab/riscv-gnu-toolchain/releases/download/2023.02.25/riscv64-elf-ubuntu-20.04-nightly-2023.02.25-nightly.tar.gz)
- [riscv64-glibc-ubuntu-20.04-nightly-2023.02.25-nightly.tar.gz](https://github.com/riscv-collab/riscv-gnu-toolchain/releases/download/2023.02.25/riscv64-glibc-ubuntu-20.04-nightly-2023.02.25-nightly.tar.gz)

**Comment by QQxiaoming** [comment]
Hi @zhutang, I tried using your toolchain. When I enter `./riscv64-unknown-elf-gcc -v` to see the result.

```
Using built-in specs.
COLLECT_GCC=./riscv64-unknown-elf-gcc
COLLECT_LTO_WRAPPER=/home/qqm/Downloads/riscv/bin/../libexec/gcc/riscv64-unknown-elf/12.2.0/lto-wrapper
Target: riscv64-unknown-elf
Configured with: /home/runner/work/riscv-gnu-toolchain/riscv-gnu-toolchain/gcc/configure --target=riscv64-unknown-elf --prefix=/opt/riscv --disable-shared --disable-threads --enable-languages=c,c++ --with-pkgversion=g2ee5e430018 --with-system-zlib --enable-tls --with-newlib --with-sysroot=/opt/riscv/riscv64-unknown-elf --with-native-system-header-dir=/include --disable-libmudflap --disable-libssp --disable-libquadmath --disable-libgomp --disable-nls --disable-tm-clone-registry --src=/home/runner/work/riscv-gnu-toolchain/riscv-gnu-toolchain/gcc --disable-multilib --with-abi=lp64d --with-arch=rv64gc --with-tune=rocket --with-isa-spec=2.2 'CFLAGS_FOR_TARGET=-Os   -mcmodel=medlow' 'CXXFLAGS_FOR_TARGET=-Os   -mcmodel=medlow'
Thread model: single
Supported LTO compression algorithms: zlib
gcc version 12.2.0 (g2ee5e430018) 
```

`-mcmodel=medlow` is not an option we need. Because trusted_fw.bin need to link to high addresses above 0x80000000.You can refer to the instructions here for the correct toolchain compilation options(sorry only in chinese).

https://github.com/QQxiaoming/quard_star_tutorial/blob/ed1c2910595cb6dbbb709cf18453b08a3e4ea281/DEVELOPNOTE.md?plain=1#L92-L102

**Comment by zhutang** [comment]
> Hi @zhutang, I tried using your toolchain. When I enter `./riscv64-unknown-elf-gcc -v` to see the result.
> 
> ```
> Using built-in specs.
> COLLECT_GCC=./riscv64-unknown-elf-gcc
> COLLECT_LTO_WRAPPER=/home/qqm/Downloads/riscv/bin/../libexec/gcc/riscv64-unknown-elf/12.2.0/lto-wrapper
> Target: riscv64-unknown-elf
> Configured with: /home/runner/work/riscv-gnu-toolchain/riscv-gnu-toolchain/gcc/configure --target=riscv64-unknown-elf --prefix=/opt/riscv --disable-shared --disable-threads --enable-languages=c,c++ --with-pkgversion=g2ee5e430018 --with-system-zlib --enable-tls --with-newlib --with-sysroot=/opt/riscv/riscv64-unknown-elf --with-native-system-header-dir=/include --disable-libmudflap --disable-libssp --disable-libquadmath --disable-libgomp --disable-nls --disable-tm-clone-registry --src=/home/runner/work/riscv-gnu-toolchain/riscv-gnu-toolchain/gcc --disable-multilib --with-abi=lp64d --with-arch=rv64gc --with-tune=rocket --with-isa-spec=2.2 'CFLAGS_FOR_TARGET=-Os   -mcmodel=medlow' 'CXXFLAGS_FOR_TARGET=-Os   -mcmodel=medlow'
> Thread model: single
> Supported LTO compression algorithms: zlib
> gcc version 12.2.0 (g2ee5e430018) 
> ```
> 
> `-mcmodel=medlow` is not an option we need. Because trusted_fw.bin need to link to high addresses above 0x80000000.You can refer to the instructions here for the correct toolchain compilation options(sorry only in chinese).
> 
> https://github.com/QQxiaoming/quard_star_tutorial/blob/ed1c2910595cb6dbbb709cf18453b08a3e4ea281/DEVELOPNOTE.md?plain=1#L92-L102

谢谢！我用你发的这个编译器（https://static.dev.sifive.com/dev-tools/freedom-tools/v2020.12/riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14.tar.gz）成功完成了trusted_domain的编译，但用这个（https://github.com/riscv/riscv-gnu-toolchain/releases/download/2021.08.07/riscv64-glibc-ubuntu-20.04-nightly-2021.08.07-nightly.tar.gz）编译器编译busybox的时候有些问题，然后切换到这个（https://github.com/riscv-collab/riscv-gnu-toolchain/releases/download/2023.02.25/riscv64-glibc-ubuntu-20.04-nightly-2023.02.25-nightly.tar.gz）编译器编译busybox和rootfs之后，就成功运行了。
