### ISSUE TITLE
build img issue

### ISSUE THREAD

**Issue by adrain-yu** [QQxiaoming/quard_star_tutorial#29]
合成img文件的时候 losetup 分区在脚本里面没有做， 需要先手动搞一波
losetup -o 0 --sizelimit 1073741824 /dev/loop70  output/rootfs/rootfs.img -P
sfdisk /dev/loop70
/dev/loop70p1 : start=        2048, size=      196608, type=c
/dev/loop70p2 : start=      198656, size=     1898496, type=83

mkfs.vfat /dev/loop70p1
mkfs.ext4 /dev/loop70p2

**Comment by QQxiaoming** [comment]
img文件构建是通过这个脚本完成的。

https://github.com/QQxiaoming/quard_star_tutorial/blob/555706cc3cc9b867a82f548c405e4a3bed286fbf/build_rootfs/generate_rootfs.sh#L1-L24

调用此脚本的位置位于

https://github.com/QQxiaoming/quard_star_tutorial/blob/555706cc3cc9b867a82f548c405e4a3bed286fbf/build.sh#L296-L299

构建时指定`BUILD_ROOTFS_OPT`为`all`就会完整构建，否则会之更新必要的部分，这里是考虑文件系统在运行中会产生新的文件，不希望在更新文件系统时破坏里面原有的文件，只进行必要的更新。

另外可以比对查看github action的完整构建/测试日志，ci每次输出的工件都是完整的映像并进行测试，应该不会遗漏需要手动执行的部分。

https://github.com/QQxiaoming/quard_star_tutorial/actions/workflows/main_ci.yml

**Comment by adrain-yu** [comment]
编译的时候使用的是./build.sh all all 指令 应该会完整创建吧

**Comment by adrain-yu** [comment]
应该是我的问题，不晓得昨天 编译为啥没有走到sdfisk创建loop流程里面， 刚才重新测试了一下，已经可以走到这里了：
Welcome to fdisk (util-linux 2.34).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

Device does not contain a recognized partition table.
Created a new DOS disklabel with disk identifier 0x4d932bcc.

Command (m for help):
Enter script file name:
Created a new DOS disklabel with disk identifier 0x32a47f23.
Created a new partition 1 of type 'W95 FAT32 (LBA)' and of size 96 MiB.
Created a new partition 2 of type 'Linux' and of size 3.9 GiB.
Script successfully applied.

多谢老哥的解答， 关闭这个issue了
