### ISSUE TITLE
about quard start GUI

### ISSUE THREAD

**Issue by DSMGuoGuo** [QQxiaoming/quard_star_tutorial#31]
Hello ，
     I want to know how the GUI and QEMU binding of quard start are implemented

**Comment by QQxiaoming** [comment]
https://github.com/QQxiaoming/quard_star_tutorial/blob/4c7dee7525a4daf003e4b515fa8619d67b73918a/quard_star_tools/src/boardview/boardwindow.cpp#L326-L345

**Comment by DSMGuoGuo** [comment]
thanks.
